export enum TASK_STATUS_ENUM {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
}

export enum TASK_PRIORITY_ENUM {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export const NUM_TASK_PRIORITY_TO_TASK_ENUM: Record<number, TASK_PRIORITY_ENUM> = {
  1: TASK_PRIORITY_ENUM.LOW,
  2: TASK_PRIORITY_ENUM.MEDIUM,
  3: TASK_PRIORITY_ENUM.HIGH,
}
