import { TASK_STATUS } from './Task'

export const Tasks = [
  {
    id: 1,
    title: 'Task 1',
    label: 'Frontend Bug',
    description: 'Fix navigation menu responsiveness',
    status: TASK_STATUS.TODO,
    priority: 'High',
    dueDate: '2024-01-15',
    isInWatchlist: true,
  },
  {
    id: 2,
    title: 'Task 2',
    label: 'Documentation',
    description: 'Update API documentation',
    status: TASK_STATUS.IN_PROGRESS,
    priority: 'Medium',
    dueDate: '2024-01-20',
    isInWatchlist: false,
  },
  {
    id: 3,
    title: 'Task 3',
    label: 'Feature',
    description: 'Implement user authentication',
    status: TASK_STATUS.PENDING,
    priority: 'High',
    dueDate: '2024-02-01',
    isInWatchlist: true,
  },
  {
    id: 4,
    title: 'Task 4',
    label: 'Testing',
    description: 'Write unit tests for dashboard components',
    status: TASK_STATUS.ACTIVE,
    priority: 'Medium',
    dueDate: '2024-01-25',
    isInWatchlist: false,
  },
  {
    id: 5,
    title: 'Task 5',
    label: 'Backend',
    description: 'Optimize database queries',
    status: TASK_STATUS.TODO,
    priority: 'Low',
    dueDate: '2024-02-10',
    isInWatchlist: true,
  },
  {
    id: 6,
    title: 'Task 6',
    label: 'UI/UX',
    description: 'Redesign landing page',
    status: TASK_STATUS.DEFERRED,
    priority: 'Low',
    dueDate: '2024-03-01',
    isInWatchlist: false,
  },
  {
    id: 7,
    title: 'Task 7',
    label: 'Performance',
    description: 'Improve page load times',
    status: TASK_STATUS.IN_PROGRESS,
    priority: 'High',
    dueDate: '2024-01-30',
    isInWatchlist: true,
  },
  {
    id: 8,
    title: 'Task 8',
    label: 'Security',
    description: 'Implement input validation',
    status: TASK_STATUS.COMPLETED,
    priority: 'High',
    dueDate: '2024-01-18',
    isInWatchlist: false,
  },
  {
    id: 9,
    title: 'Task 9',
    label: 'Maintenance',
    description: 'Update dependencies',
    status: TASK_STATUS.TODO,
    priority: 'Medium',
    dueDate: '2024-02-05',
    isInWatchlist: true,
  },
  {
    id: 10,
    title: 'Task 10',
    label: 'Integration',
    description: 'Connect with third-party API',
    status: TASK_STATUS.ACTIVE,
    priority: 'Medium',
    dueDate: '2024-02-15',
    isInWatchlist: false,
  },
]
